name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Necessary for SonarCloud to analyze all history

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze with Maven and SonarCloud
        run: 
          mvn verify sonar:sonar -Pcoverage -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: Find JaCoCo coverage reports
        run: find ./target/ -name 'jacoco*.csv'

      - name: Print JaCoCo Coverage Summary
        run: |
          JACOCO_CSV=$(find ./target/ -name 'jacoco*.csv')
          if [[ -n "$JACOCO_CSV" ]]; then
            cat "$JACOCO_CSV"
          else
            echo "No JaCoCo CSV report found."
          fi

      - name: Upload target folder as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: project-artifacts
          path: target/
          if-no-files-found: error # Optional: "warn" or "ignore" (default "warn")
