name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Necessary for SonarCloud to analyze all history

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Display Java version
        run: java -version

      - name: Display Maven version
        run: mvn -version
        
      - name: Generate JaCoCo Report Manually
        run: mvn org.jacoco:jacoco-maven-plugin:report

      - name: Build with Coverage Profile
        run: mvn clean verify -Pcoverage -e
        
      - name: List Target Directory
        run: ls -alh ./target/
        
      - name: List JaCoCo Directory
        run: ls -alR ./target/

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze with Maven and SonarCloud
        run: mvn clean verify sonar:sonar -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{ secrets.SONAR_TOKEN }} -Pcoverage -Dsonar.coverage.jacoco.xmlReportPaths=./target/site/jacoco/jacoco.xml
